version: "3.2"

services:

  envtest:
    build:
      context: .
      dockerfile: Dockerfile
    image: envtest:latest
    container_name: envtest
    ports:
      - "8080:80"
    environment:
      - VUE_APP_VARIABLE_1=$VUE_APP_VARIABLE_1 
      - VUE_APP_VARIABLE_2=$VUE_APP_VARIABLE_2
